namespace WebAPIApplicationProject.Models
{
    public class PlantFood
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string ScientificName { get; set; }
        public string[] Provenance { get; set; } = [];
        public string Season { get; set; }
        public bool IsSeasonal { get; set; }
        public bool IsVegetable { get; set; }
        public string? ImageUrl { get; set; } = null;
    }

    // pour avoir de la donnée par défaut pour pouvoir tester et avoir un environnement plus réaliste
    public class PlantFoodConstants
    {
        public static List<PlantFood> DefaultPlantFood = new List<PlantFood>()
        {
            new PlantFood { Id = 1, Name = "Pomme", ScientificName = "Malus domestica", Provenance = new[] { "Europe" }, Season = "Automne", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2022/05/18/15/44/apple-7205616_1280.jpg" },
            new PlantFood { Id = 2, Name = "Poire", ScientificName = "Pyrus communis", Provenance = new[] { "Europe" }, Season = "Automne", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2019/09/15/18/32/fruit-4479075_1280.jpg" },
            new PlantFood { Id = 3, Name = "Banane", ScientificName = "Musa spp.", Provenance = new[] { "Asie", "Afrique" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2015/11/05/23/08/banana-1025109_1280.jpg" },
            new PlantFood { Id = 4, Name = "Orange", ScientificName = "Citrus × sinensis", Provenance = new[] { "Méditerranée" }, Season = "Hiver", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2017/04/04/17/42/fruits-2202426_1280.jpg" },
            new PlantFood { Id = 5, Name = "Citron", ScientificName = "Citrus limon", Provenance = new[] { "Méditerranée" }, Season = "Hiver", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2017/06/16/14/35/lemon-2409365_1280.jpg" },
            new PlantFood { Id = 6, Name = "Tomate", ScientificName = "Solanum lycopersicum", Provenance = new[] { "Amérique du Sud" }, Season = "Été", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2019/07/11/10/14/cherry-tomato-4330441_960_720.jpg" },
            new PlantFood { Id = 7, Name = "Carotte", ScientificName = "Daucus carota", Provenance = new[] { "Europe" }, Season = "Automne", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2020/06/23/23/40/carrot-5334163_960_720.jpg" },
            new PlantFood { Id = 8, Name = "Courgette", ScientificName = "Cucurbita pepo", Provenance = new[] { "Amérique Centrale" }, Season = "Été", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2015/09/07/19/31/still-life-928953_1280.jpg" },
            new PlantFood { Id = 9, Name = "Aubergine", ScientificName = "Solanum melongena", Provenance = new[] { "Asie" }, Season = "Été", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2017/09/17/21/38/ripe-eggplant-2759947_1280.jpg" },
            new PlantFood { Id = 10, Name = "Poivron", ScientificName = "Capsicum annuum", Provenance = new[] { "Amérique du Sud" }, Season = "Été", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2014/10/22/21/54/bell-peppers-499068_1280.jpg" },
            new PlantFood { Id = 11, Name = "Concombre", ScientificName = "Cucumis sativus", Provenance = new[] { "Asie" }, Season = "Été", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2015/03/23/08/04/cucumber-685704_1280.jpg" },
            new PlantFood { Id = 12, Name = "Radis", ScientificName = "Raphanus sativus", Provenance = new[] { "Europe" }, Season = "Printemps", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2021/10/31/14/37/radishes-6757642_1280.jpg" },
            new PlantFood { Id = 13, Name = "Betterave", ScientificName = "Beta vulgaris", Provenance = new[] { "Europe" }, Season = "Automne", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2015/03/24/08/52/beetroot-687251_1280.jpg" },
            new PlantFood { Id = 14, Name = "Laitue", ScientificName = "Lactuca sativa", Provenance = new[] { "Europe" }, Season = "Printemps", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2015/05/17/14/29/salad-771056_1280.jpg" },
            new PlantFood { Id = 15, Name = "Chou-fleur", ScientificName = "Brassica oleracea", Provenance = new[] { "Europe" }, Season = "Hiver", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2014/04/07/01/46/cauliflower-318152_1280.jpg" },
            new PlantFood { Id = 16, Name = "Brocoli", ScientificName = "Brassica oleracea", Provenance = new[] { "Europe" }, Season = "Hiver", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2023/01/25/18/46/broccoli-7744338_1280.jpg" },
            new PlantFood { Id = 17, Name = "Épinard", ScientificName = "Spinacia oleracea", Provenance = new[] { "Asie" }, Season = "Printemps", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2018/06/08/22/16/spinach-3463248_1280.jpg" },
            new PlantFood { Id = 18, Name = "Chou rouge", ScientificName = "Brassica oleracea", Provenance = new[] { "Europe" }, Season = "Hiver", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2016/04/19/05/56/red-cabbage-1338061_1280.jpg" },
            new PlantFood { Id = 19, Name = "Chou vert", ScientificName = "Brassica oleracea", Provenance = new[] { "Europe" }, Season = "Hiver", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2022/03/31/12/27/savoy-cabbage-7102903_1280.jpg" },
            new PlantFood { Id = 20, Name = "Navet", ScientificName = "Brassica rapa", Provenance = new[] { "Europe" }, Season = "Automne", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2018/02/04/04/45/root-3129065_1280.jpg" },
            new PlantFood { Id = 21, Name = "Fraise", ScientificName = "Fragaria × ananassa", Provenance = new[] { "Europe" }, Season = "Printemps", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2022/05/27/10/35/strawberry-7224875_1280.jpg" },
            new PlantFood { Id = 22, Name = "Framboise", ScientificName = "Rubus idaeus", Provenance = new[] { "Europe" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2015/09/01/22/18/raspberries-917664_1280.jpg" },
            new PlantFood { Id = 23, Name = "Mûre", ScientificName = "Rubus fruticosus", Provenance = new[] { "Europe" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2016/07/24/23/35/blackberries-1539540_1280.jpg" },
            new PlantFood { Id = 24, Name = "Cerise", ScientificName = "Prunus avium", Provenance = new[] { "Europe" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2018/07/14/22/59/cherries-3538623_1280.jpg" },
            new PlantFood { Id = 25, Name = "Prune", ScientificName = "Prunus domestica", Provenance = new[] { "Europe" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2016/08/01/16/45/plum-1561529_1280.jpg" },
            new PlantFood { Id = 26, Name = "Abricot", ScientificName = "Prunus armeniaca", Provenance = new[] { "Asie", "Europe" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2019/05/17/21/22/apricots-4210720_1280.jpg" },
            new PlantFood { Id = 27, Name = "Pêche", ScientificName = "Prunus persica", Provenance = new[] { "Asie" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2017/08/11/17/41/peach-2632182_1280.jpg" },
            new PlantFood { Id = 28, Name = "Melon", ScientificName = "Cucumis melo", Provenance = new[] { "Afrique" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2012/01/06/02/40/cantaloupe-11541_1280.jpg" },
            new PlantFood { Id = 29, Name = "Pastèque", ScientificName = "Citrullus lanatus", Provenance = new[] { "Afrique" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2023/09/29/07/58/watermelon-8283269_1280.jpg" },
            new PlantFood { Id = 30, Name = "Mangue", ScientificName = "Mangifera indica", Provenance = new[] { "Asie" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2016/03/05/22/41/mango-1239347_1280.jpg" },
            new PlantFood { Id = 31, Name = "Avocat", ScientificName = "Persea americana", Provenance = new[] { "Amérique Centrale" }, Season = "Hiver", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2015/08/10/12/02/avocados-882635_1280.jpg" },
            new PlantFood { Id = 32, Name = "Noix de coco", ScientificName = "Cocos nucifera", Provenance = new[] { "Asie" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2016/07/06/20/56/coconut-1501334_1280.jpg" },
            new PlantFood { Id = 33, Name = "Ananas", ScientificName = "Ananas comosus", Provenance = new[] { "Amérique du Sud" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2018/11/11/15/42/pineapple-3808963_1280.jpg" },
            new PlantFood { Id = 34, Name = "Kiwi", ScientificName = "Actinidia deliciosa", Provenance = new[] { "Asie" }, Season = "Hiver", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2014/07/23/11/51/kiwifruit-400143_1280.jpg" },
            new PlantFood { Id = 35, Name = "Papaye", ScientificName = "Carica papaya", Provenance = new[] { "Amérique Centrale" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2015/10/01/00/31/papaya-966322_1280.jpg" },
            new PlantFood { Id = 36, Name = "Figue", ScientificName = "Ficus carica", Provenance = new[] { "Méditerranée" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2010/12/14/10/31/fig-3073_1280.jpg" },
            new PlantFood { Id = 37, Name = "Grenade", ScientificName = "Punica granatum", Provenance = new[] { "Méditerranée" }, Season = "Automne", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2013/10/17/10/59/pomegranate-196800_1280.jpg" },
            new PlantFood { Id = 38, Name = "Patate douce", ScientificName = "Ipomoea batatas", Provenance = new[] { "Amérique du Sud" }, Season = "Automne", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2017/01/12/23/49/sweetpotato-1975990_1280.jpg" },
            new PlantFood { Id = 39, Name = "Pomme de terre", ScientificName = "Solanum tuberosum", Provenance = new[] { "Amérique du Sud" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2016/08/11/08/49/potatoes-1585075_1280.jpg" },
            new PlantFood { Id = 40, Name = "Oignon", ScientificName = "Allium cepa", Provenance = new[] { "Asie" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2013/02/21/19/14/onion-bulbs-84722_1280.jpg" },
            new PlantFood { Id = 41, Name = "Ail", ScientificName = "Allium sativum", Provenance = new[] { "Asie" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2013/02/21/19/12/garlic-84691_1280.jpg" },
            new PlantFood { Id = 42, Name = "Poireau", ScientificName = "Allium ampeloprasum", Provenance = new[] { "Europe" }, Season = "Hiver", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2017/08/17/22/28/leek-2653127_1280.jpg" },
            new PlantFood { Id = 43, Name = "Céleri", ScientificName = "Apium graveolens", Provenance = new[] { "Europe" }, Season = "Hiver", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2015/03/30/19/41/celery-700084_1280.jpg" },
            new PlantFood { Id = 44, Name = "Fenouil", ScientificName = "Foeniculum vulgare", Provenance = new[] { "Europe" }, Season = "Automne", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2016/04/06/12/39/fennel-1311691_1280.jpg" },
            new PlantFood { Id = 45, Name = "Haricot vert", ScientificName = "Phaseolus vulgaris", Provenance = new[] { "Amérique du Sud" }, Season = "Été", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2016/06/08/06/31/green-bean-1443290_1280.jpg" },
            new PlantFood { Id = 46, Name = "Petit pois", ScientificName = "Pisum sativum", Provenance = new[] { "Europe" }, Season = "Printemps", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2013/06/03/18/05/peas-115951_1280.jpg" },
            new PlantFood { Id = 47, Name = "Maïs", ScientificName = "Zea mays", Provenance = new[] { "Amérique Centrale" }, Season = "Été", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2015/05/26/17/42/pop-corn-785074_1280.jpg" },
            new PlantFood { Id = 48, Name = "Pois chiche", ScientificName = "Cicer arietinum", Provenance = new[] { "Moyen-Orient" }, Season = "Été", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2019/08/10/08/39/chickpeas-4396439_1280.jpg" },
            new PlantFood { Id = 49, Name = "Lentille", ScientificName = "Lens culinaris", Provenance = new[] { "Moyen-Orient" }, Season = "Automne", IsSeasonal = true, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2015/11/24/09/31/lens-1059702_1280.jpg" },
            new PlantFood { Id = 50, Name = "Riz", ScientificName = "Oryza sativa", Provenance = new[] { "Asie" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2017/06/07/16/24/rice-2380808_1280.jpg" },
            new PlantFood { Id = 51, Name = "Blé", ScientificName = "Triticum aestivum", Provenance = new[] { "Asie" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2023/07/30/07/23/soft-wheat-8158264_1280.jpg" },
            new PlantFood { Id = 52, Name = "Seigle", ScientificName = "Secale cereale", Provenance = new[] { "Europe" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2021/06/30/04/18/rye-6375839_1280.jpg" },
            new PlantFood { Id = 53, Name = "Orge", ScientificName = "Hordeum vulgare", Provenance = new[] { "Europe" }, Season = "Toute l'année", IsSeasonal = false, IsVegetable = true, ImageUrl = "https://cdn.pixabay.com/photo/2018/06/12/22/08/foxtail-barley-3471611_1280.jpg" },
            new PlantFood { Id = 54, Name = "Noisette", ScientificName = "Corylus avellana", Provenance = new[] { "Europe" }, Season = "Automne", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2016/10/01/14/00/hazelnuts-1707601_1280.jpg" },
            new PlantFood { Id = 55, Name = "Amande", ScientificName = "Prunus dulcis", Provenance = new[] { "Méditerranée" }, Season = "Automne", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2013/02/20/11/30/almond-83766_960_720.jpg" },
            new PlantFood { Id = 56, Name = "Noix", ScientificName = "Juglans regia", Provenance = new[] { "Europe" }, Season = "Automne", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2013/04/07/10/31/walnuts-101425_1280.jpg" },
            new PlantFood { Id = 57, Name = "Châtaigne", ScientificName = "Castanea sativa", Provenance = new[] { "Europe" }, Season = "Automne", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2016/10/03/00/33/chestnut-1710748_1280.jpg" },
            new PlantFood { Id = 58, Name = "Cassis", ScientificName = "Ribes nigrum", Provenance = new[] { "Europe" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2021/08/31/15/33/berries-6589126_1280.jpg" },
            new PlantFood { Id = 59, Name = "Groseille", ScientificName = "Ribes rubrum", Provenance = new[] { "Europe" }, Season = "Été", IsSeasonal = true, IsVegetable = false, ImageUrl = "https://cdn.pixabay.com/photo/2019/08/18/15/41/fruit-4414346_1280.jpg" },
        };
    }
}
